server:
  port: 8680
  servlet:
    context-path: /kite-cine

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432}/kite-cine
    driverClassName: "org.postgresql.Driver"
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:postgres}

    hikari:
      maximum-pool-size: 30
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

email-services:
  senders:
    - name: KITECINE
      sender-name: Kite Cine
      sender-email: kitecine@hph.id.vn
  brevo:
    url: https://api.brevo.com
    apikey: ${BREVO_API_KEY:brevokey}
storage:
  location: ./files
  url: ${MEDIA_DOWNLOAD_URL:http://localhost:8680/kite-cine/media}

jwt:
  signerKey: ${JWT_SIGNER_KEY:signer-key}
  valid-duration: 30000 # in second
  refreshable-duration: 36000 # in seconds
